version: '3.3'

services:
    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        environment:
            - BACKEND_URL=http://web
        volumes:
            - './spa:/app'
            - '/app/node_modules'
        ports:
            - 80:5000
        networks:
            - accounts

    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./docker/php/default.conf:/etc/nginx/conf.d/default.conf
            - ./api:/api
        ports:
            - 8080:80
        depends_on:
            - php
        networks:
            - accounts

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./api:/api
        env_file:
            - ../docker/mysql/.env
        environment:
            - MYSQL_DATABASE=accounts
        networks:
            - accounts

networks:
    accounts:
        external: true
